# Default values for demoApi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "ychafiki/bpm-sample"
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 8080

imageCredentials:
  registry: registry.gitlab.com
  username: username
  password: password



