apiVersion: v1
kind: Secret
metadata:
  name: {{ template "camunda-engine.fullname" . }}
  labels:
    app: {{ template "camunda-engine.name" . }}
    chart: {{ template "camunda-engine.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
